on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Get PR Diff
        run: |
          PR_NUMBER=${{ github.event.number }}
          DIFF=$(git diff --name-only origin/main "pull/${PR_NUMBER}/head")
          echo "::set-env name=PR_DIFF::$DIFF"
 
      - name: Print PR Diff
        run: |
          echo "PR Diff: $PR_DIFF"
