on: 
  pull_request: 
    types: [opened, synchronize]   
permissions:
     actions: read

jobs: 

  build: 

    runs-on: ubuntu-latest 
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      REVIEWER_DETAILS: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Reviewer
        run: |
          echo "reviewr:${{ github.repository_owner }}"
        
     
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
          
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
          
          #PULL_NUMBER="${{ github.event.pull_request.number }}"
      - name: Send details to API
        run: |
          COMMENT="PR author: ${PR_AUTHOR_GITHUB_ID}\nReviewer: $REVIEWER_DETAILS\nPR URL: ${{ github.event.pull_request.html_url }}\n\nDiff content:\n$(cat mydiff)"
          echo "Comment content:\n$COMMENT"

          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "${{ github.event.pull_request.comments_url }}"
          

        
          
