on: 
  pull_request: 
    types: [opened, synchronize]   
permissions:
     actions: read

jobs: 

  build: 

    runs-on: ubuntu-latest 
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      GH_TOKEN: ${{ github.token }}
      
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Get reviewer details
        id: get_reviewers
        run: |
          REVIEWER_DETAILS=$(curl -s -H "Authorization: $GH_TOKEN" \
            "https://api.github.com/repos/AkhilaPodilapu5/DemoPR/pulls/4/reviews" | jq -r '.[].user.login // empty' | uniq)
          echo "Reviewers: $REVIEWER_DETAILS"
          echo "Reviewers: $REVIEWER_DETAILS" > reviewers.txt
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
      - name: Print diff 
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff.diff
          

        
          
