name: Get PR Diff Info
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Get PR Info
        id: pr_info
        run: |
          PR_NUMBER=${{ github.event.number }}
          SOURCE_BRANCH=$(git show --no-patch --format='%H' "refs/pull/$PR_NUMBER/head")
          TARGET_BRANCH=$(git show --no-patch --format='%H' "refs/pull/$PR_NUMBER/base")
          echo "::set-output name=source_branch::$SOURCE_BRANCH"
          echo "::set-output name=target_branch::$TARGET_BRANCH"
          echo "::set-output name=pr_id::$PR_NUMBER"
 
      - name: Fetch source branch
        run: git fetch origin ${{ steps.pr_info.outputs.source_branch }}:${{ steps.pr_info.outputs.source_branch }}
 
      - name: Fetch target branch
        run: git fetch origin ${{ steps.pr_info.outputs.target_branch }}:${{ steps.pr_info.outputs.target_branch }}
 
      - name: Get PR Diff
        run: |
          SOURCE_BRANCH=${{ steps.pr_info.outputs.source_branch }}
          TARGET_BRANCH=${{ steps.pr_info.outputs.target_branch }}
          PR_NUMBER=${{ steps.pr_info.outputs.pr_id }}
          DIFF=$(git diff --name-only $TARGET_BRANCH $SOURCE_BRANCH)
          echo "::set-output name=diff::$DIFF"
 
      - name: Print PR Diff
        run: |
          echo "PR Diff: ${{ steps.pr_diff.outputs.diff }}"
     
