on: 
  pull_request: 
    types: [opened, synchronize]   

jobs: 

  build: 

    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

   
    - name: Get PR diff 
      # Check the PR diff using the current branch and the base branch of the PR
      uses: GrantBirki/git-diff-action@vX.X.X
      id: git-diff-action
      with:
        json_diff_file_output: diff.json
        raw_diff_file_output: diff.txt
        file_output_only: "true"

      # Print the diff in JSON format
    - name: print json diff
      env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
          run: cat $DIFF
