jobs:
  pr_data:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR data
        run: |
          # Fetch user information using GitHub REST API
          USER_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.event.pull_request.user.login }}")
          USER_EMAIL=$(echo "$USER_DATA" | jq -r '.email // "Email not public"')

          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "PR author email: $USER_EMAIL" > generated_data.txt
          echo "Reviewer: ${{ github.repository_owner }}" >> generated_data.txt
          echo "Pull Request URL: ${{ github.event.pull_request.html_url }}" >> generated_data.txt
          cat generated_data.txt

          # Exit with an error if email is null
          if [ "$USER_EMAIL" = "null" ]; then
            echo "Error: Contributor has not made their email address public."
            exit 1
          fi

      - name: Send PR data to API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "@generated_data.txt" \
            "https://httpbin.org/anything"

     
      
          

        
          
