on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      REVIEWER_DETAILS: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Generate data
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}" > generated_data.txt
          echo "reviewr: ${REVIEWER_DETAILS}" >> generated_data.txt
          echo "Pull Request URL: ${{ github.event.pull_request.html_url }}" >> generated_data.txt
          cat generated_data.txt

      - name: Checkout pull request HEAD
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Print diff
        run: |
          git fetch origin main
          git diff origin/main..HEAD > diff_data.txt
          echo "mydiff = $(cat diff_data.txt)"
          cat diff_data.txt

      - name: Send data to API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "@./generated_data.txt" \
            "https://httpbin.org/anything"

          curl -X POST \
            -H "Content-Type: text/plain" \
            -d "@./diff_data.txt" \
            "https://httpbin.org/anything"
