name: Get PR Diff Info
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Get default branch name
        run: |
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          echo "::set-env name=DEFAULT_BRANCH::$DEFAULT_BRANCH"
 
      - name: Fetch default branch
        run: git fetch origin $DEFAULT_BRANCH:$DEFAULT_BRANCH
 
      - name: Get PR Diff
        run: |
          PR_NUMBER=${{ github.event.number }}
          DIFF=$(git diff --name-only $DEFAULT_BRANCH "refs/pull/$PR_NUMBER/head")
          echo "::set-env name=PR_DIFF::$DIFF"
 
      - name: Print PR Diff
        run: |
          echo "PR Diff: $PR_DIFF"
