on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read
  actions: write
jobs:
  pr_data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch author information
        run: |
          AUTHOR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.event.pull_request.user.login }}")
          AUTHOR_ID=$(echo "$AUTHOR_DATA" | jq -r .id)

          # Exit with an error if ID is null
          if [ "$AUTHOR_ID" = "null" ]; then
            echo "Error: Unable to fetch user ID for PR author."
            exit 1
          fi

      - name: Fetch owner information
        run: |
          OWNER_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}")
          OWNER_ID=$(echo "$OWNER_DATA" | jq -r .id)

          # Exit with an error if ID is null
          if [ "$OWNER_ID" = "null" ]; then
            echo "Error: Unable to fetch user ID for repository owner."
            exit 1
          fi

      - name: Generate PR data
        run: |
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "PR author ID: $AUTHOR_ID" > generated_data.txt
          echo "Reviewer: ${{ github.repository_owner }}"
          echo "Reviewer ID: $OWNER_ID" >> generated_data.txt
          echo "Pull Request URL: ${{ github.event.pull_request.html_url }}" >> generated_data.txt
          cat generated_data.txt

      - name: Send PR data to API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "@generated_data.txt" \
            "https://httpbin.org/anything"
     
        
          
