on: 
  pull_request: 
    types: [opened, synchronize]   
permissions:
     actions: read

jobs: 

  build: 

    runs-on: ubuntu-latest 
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Get reviewer details
        id: get_reviewers
        run: |
          REVIEWER_DETAILS=$(curl -s -H "Authorization: $GITHUB_TOKEN" "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" | jq -r '.users[].login // empty')
          echo "Reviewers: $REVIEWER_DETAILS"
          echo "Reviewers: $REVIEWER_DETAILS" > reviewers.txt
          
          
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Print diff 
      
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff.diff
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/OWNER/REPO/pulls


          

        
          
