name: Get PR Diff Info
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Get PR Diff
        run: |
          PR_NUMBER=${{ github.event.number }}
          gh pr diff PR_NUMBER
 
     
