on: 
  pull_request: 
    types: [opened, synchronize]   

jobs: 

  build: 

    runs-on: ubuntu-latest 
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.url}}
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
          echo "Pull Request URL: ${{ PR_URL }}"
          
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Print diff 
      
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff.diff

          

        
          
