on: 
  pull_request: 
    types: [opened, synchronize]   
permissions:
     actions: read

jobs: 

  build: 

    runs-on: ubuntu-latest 
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      REVIEWER_DETAILS: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Reviewer
        run: |
          echo "reviewr:${{ github.repository_owner }}"
        
     
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
          
      - name: Print diff 
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff.diff
          PULL_NUMBER="${{ github.event.pull_request.number }}"
          
          API_URL="https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PULL_NUMBER}"
          PULL_REQUEST_DETAILS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" $API_URL)
          
          echo "Pull Request Details: $PULL_REQUEST_DETAILS"

      
          

        
          
