on: 
  pull_request: 
    types: [opened, synchronize]   
permissions:
     actions: read

jobs: 

  build: 

    runs-on: ubuntu-latest 
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
      REVIEWER_DETAILS: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Reviewer
        run: |
          echo "reviewr:${{ github.repository_owner }}"
      - name: Get Pull Request URL
        run: |
         echo "Pull Request URL: ${{ github.event.pull_request.html_url }}"
     
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
          
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
          
      - name: Grant execute permissions to script
        run: chmod +x generate_payload.sh

      - name: Generate payload
        run: |
          ./generate_payload.sh
          echo "Generated payload:"
          cat payload.json
        
      - name: Send data to API
        run: |
          curl -X POST \
           -H "Content-Type: application/json" \
           -d "$(cat payload.json)" \
           "https://httpbin.org/anything"   
      
          

        
          
