on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read
  actions: write

jobs:
  pr_data:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR data
        run: |
          echo "PR author: ${{ github.event.pull_request.user.login }}" > $HOME/pr_data.txt
          echo "Reviewer: ${{ github.repository_owner }}" >> $HOME/pr_data.txt
          echo "Pull Request URL: ${{ github.event.pull_request.html_url }}" >> $HOME/pr_data.txt
          cat $HOME/pr_data.txt

      - name: Send PR data to API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "@$HOME/pr_data.txt" \
            "https://httpbin.org/anything"

  diff_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request HEAD
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Generate diff
        run: |
          git fetch origin main
          git diff origin/main..HEAD > $HOME/diff_data.txt
          echo "mydiff = $(cat $HOME/diff_data.txt)"
          cat $HOME/diff_data.txt

      - name: Send diff data to API
        run: |
          curl -X POST \
            -H "Content-Type: text/plain" \
            -d "@$HOME/diff_data.txt" \
            "https://httpbin.org/anything"
