name: Get PR Diff Info
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Fetch pull request branch
        run: git fetch origin "refs/pull/${{ github.event.number }}/head:pr-${{ github.event.number }}"
 
      - name: Get PR Diff
        run: |
          DIFF=$(git diff --name-only main "pr-${{ github.event.number }}")
          echo "::set-env name=PR_DIFF::$DIFF"
 
      - name: Print PR Diff
        run: |
          echo "PR Diff: $PR_DIFF"
